name: "PR Analytics"
on:
  workflow_dispatch:
    inputs:
      amount:
        description: "Amount of PRs"
        required: false
        default: "100"
      report_date_start:
        description: "Report date start(d/MM/yyyy)"
        required: false
      report_date_end:
        description: "Report date end(d/MM/yyyy)"
        required: false
      aggregate_value_methods:
        description: "Aggregate value methods for timelines separated by comma. Can take values average, percentile, medianÏ"
        default: "percentile"
      percentile:
        description: "Percentile"
        required: false
        default: "75"
      issue_title:
        description: "Issue custom title"
        required: false
      labels:
        description: "Issue labels"
        required: false
      hide_users:
        description: "Hidden users"
        required: false
      show_users:
        description: "Shown users"
        required: false
      exclude_labels:
        description: "Labels to exclude"
        required: false
jobs:
  create-report:
    name: "Create report"
    runs-on: ubuntu-latest
    steps:
      - name: "Run script for analytics"
        uses: AlexSim93/pr-full-report-action@v1.3.1
        with:
          GITHUB_TOKEN: ${{ secrets.KEY }}
          ISSUE_TITLE: ${{ inputs.issue_title }}
          ASSIGNEES: "user-1, user-2, user-3"
          LABELS: ${{ inputs.labels }}
          GITHUB_REPO_FOR_ISSUE: "repo"
          GITHUB_OWNER_FOR_ISSUE: "owner"
          GITHUB_OWNERS_REPOS: "owner-1/repo-1"
          CORE_HOURS_START: "9:00"
          CORE_HOURS_END: "19:00"
          TIMEZONE: "Europe/Berlin"
          AGGREGATE_VALUE_METHODS: ${{inputs.aggregate_value_methods}}
          PERCENTILE: ${{ inputs.percentile }}
          AMOUNT: ${{ inputs.amount }}
          REPORT_DATE_START: ${{ inputs.report_date_start }}
          REPORT_DATE_END: ${{ inputs.report_date_end }}
          HIDE_USERS: ${{ inputs.hide_users }}
